window.ATLASPI_CITY_DATA = {
    "Afghanistan": ["Kabul", "Herat", "Kandahar", "Mazar-i-Sharif", "Jalalabad"],
    "Albania": ["Tirana", "Durres", "Vlore", "Shkoder", "Elbasan"],
    "Algeria": ["Algiers", "Oran", "Constantine", "Annaba", "Blida"],
    "Argentina": ["Buenos Aires", "Cordoba", "Rosario", "Mendoza", "La Plata"],
    "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
    "Austria": ["Vienna", "Graz", "Linz", "Salzburg", "Innsbruck"],
    "Bangladesh": ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
    "Belgium": ["Brussels", "Antwerp", "Ghent", "Charleroi", "Liege"],
    "Benin": ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Djougou"],
    "Bolivia": ["Santa Cruz", "La Paz", "Cochabamba", "Sucre", "Oruro"],
    "Botswana": ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe"],
    "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza", "Belo Horizonte", "Manaus", "Curitiba", "Recife", "Porto Alegre"],
    "Bulgaria": ["Sofia", "Plovdiv", "Varna", "Burgas", "Ruse"],
    "Burkina Faso": ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Ouahigouya", "Banfora"],
    "Burundi": ["Bujumbura", "Gitega", "Ngozi", "Rumonge", "Muyinga"],
    "Cambodia": ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampot"],
    "Cameroon": ["Douala", "Yaounde", "Garoua", "Bamenda", "Bafoussam"],
    "Canada": ["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa", "Edmonton", "Quebec City", "Winnipeg"],
    "Chad": ["N'Djamena", "Moundou", "Sarh", "Abeche", "Kelo"],
    "Chile": ["Santiago", "Valparaiso", "Concepcion", "La Serena", "Antofagasta"],
    "China": ["Beijing", "Shanghai", "Guangzhou", "Shenzhen", "Chengdu", "Wuhan", "Hangzhou", "Nanjing"],
    "Colombia": ["Bogota", "Medellin", "Cali", "Barranquilla", "Cartagena"],
    "Congo": ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Ouesso"],
    "Costa Rica": ["San Jose", "Limon", "Alajuela", "Heredia", "Cartago"],
    "Croatia": ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
    "Czech Republic": ["Prague", "Brno", "Ostrava", "Plzen", "Liberec"],
    "Democratic Republic of the Congo": ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Goma"],
    "Denmark": ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
    "Djibouti": ["Djibouti", "Ali Sabieh", "Tadjoura", "Obock", "Dikhil"],
    "Egypt": ["Cairo", "Alexandria", "Giza", "Luxor", "Aswan", "Mansoura"],
    "Ethiopia": ["Addis Ababa", "Dire Dawa", "Mekelle", "Adama", "Bahir Dar"],
    "Finland": ["Helsinki", "Espoo", "Tampere", "Vantaa", "Turku"],
    "France": ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Strasbourg", "Montpellier", "Bordeaux", "Lille"],
    "Gabon": ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"],
    "Gambia": ["Banjul", "Serekunda", "Brikama", "Bakau", "Farafenni"],
    "Germany": ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Dusseldorf"],
    "Ghana": ["Accra", "Kumasi", "Tamale", "Takoradi", "Cape Coast", "Tema", "Koforidua", "Ho", "Wa", "Bolgatanga"],
    "Greece": ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
    "Guinea": ["Conakry", "Kankan", "Kindia", "Labe", "N'Zerekore"],
    "India": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"],
    "Indonesia": ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
    "Iran": ["Tehran", "Mashhad", "Isfahan", "Karaj", "Shiraz"],
    "Iraq": ["Baghdad", "Basra", "Mosul", "Erbil", "Najaf"],
    "Ireland": ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
    "Israel": ["Jerusalem", "Tel Aviv", "Haifa", "Rishon LeZion", "Petah Tikva"],
    "Italy": ["Rome", "Milan", "Naples", "Turin", "Palermo", "Bologna", "Florence"],
    "Ivory Coast": ["Abidjan", "Yamoussoukro", "Bouake", "San Pedro", "Korhogo"],
    "Japan": ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo", "Fukuoka", "Kyoto", "Kobe", "Sendai", "Hiroshima"],
    "Jordan": ["Amman", "Zarqa", "Irbid", "Aqaba", "Madaba"],
    "Kazakhstan": ["Almaty", "Astana", "Shymkent", "Aktobe", "Karaganda"],
    "Kenya": ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret", "Thika", "Malindi", "Kitale", "Garissa", "Nyeri"],
    "Kuwait": ["Kuwait City", "Hawalli", "Farwaniya", "Salmiya", "Ahmadi"],
    "Lebanon": ["Beirut", "Tripoli", "Sidon", "Tyre", "Jounieh"],
    "Liberia": ["Monrovia", "Gbarnga", "Kakata", "Bensonville", "Harper"],
    "Libya": ["Tripoli", "Benghazi", "Misrata", "Sabha", "Zawiya"],
    "Madagascar": ["Antananarivo", "Toamasina", "Antsirabe", "Mahajanga", "Fianarantsoa"],
    "Malawi": ["Lilongwe", "Blantyre", "Mzuzu", "Zomba", "Kasungu"],
    "Malaysia": ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Kota Kinabalu"],
    "Mali": ["Bamako", "Sikasso", "Mopti", "Segou", "Kayes"],
    "Mauritania": ["Nouakchott", "Nouadhibou", "Rosso", "Kaedi", "Atar"],
    "Mauritius": ["Port Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"],
    "Mexico": ["Mexico City", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
    "Morocco": ["Casablanca", "Rabat", "Marrakech", "Fes", "Tangier", "Agadir", "Meknes", "Oujda", "Kenitra", "Tetouan", "Safi", "El Jadida"],
    "Mozambique": ["Maputo", "Beira", "Nampula", "Matola", "Quelimane"],
    "Namibia": ["Windhoek", "Walvis Bay", "Swakopmund", "Oshakati", "Rundu"],
    "Nepal": ["Kathmandu", "Pokhara", "Lalitpur", "Biratnagar", "Bharatpur"],
    "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven"],
    "New Zealand": ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
    "Niger": ["Niamey", "Zinder", "Maradi", "Agadez", "Tahoua"],
    "Nigeria": ["Lagos", "Abuja", "Kano", "Ibadan", "Port Harcourt", "Benin City", "Kaduna", "Jos", "Ilorin", "Enugu"],
    "Norway": ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen"],
    "Pakistan": ["Karachi", "Lahore", "Islamabad", "Rawalpindi", "Faisalabad"],
    "Peru": ["Lima", "Arequipa", "Trujillo", "Cusco", "Chiclayo"],
    "Philippines": ["Manila", "Quezon City", "Davao", "Cebu", "Zamboanga"],
    "Poland": ["Warsaw", "Krakow", "Lodz", "Wroclaw", "Poznan"],
    "Portugal": ["Lisbon", "Porto", "Braga", "Coimbra", "Faro"],
    "Qatar": ["Doha", "Al Rayyan", "Al Wakrah", "Al Khor", "Umm Salal"],
    "Romania": ["Bucharest", "Cluj-Napoca", "Timisoara", "Iasi", "Constanta"],
    "Russia": ["Moscow", "Saint Petersburg", "Novosibirsk", "Yekaterinburg", "Kazan"],
    "Rwanda": ["Kigali", "Butare", "Gitarama", "Ruhengeri", "Gisenyi"],
    "Saudi Arabia": ["Riyadh", "Jeddah", "Mecca", "Medina", "Dammam"],
    "Senegal": ["Dakar", "Touba", "Thies", "Saint-Louis", "Mbour", "Kaolack", "Ziguinchor", "Diourbel", "Louga", "Tambacounda"],
    "Serbia": ["Belgrade", "Novi Sad", "Nis", "Kragujevac", "Subotica"],
    "Sierra Leone": ["Freetown", "Bo", "Kenema", "Makeni", "Koidu"],
    "Singapore": ["Singapore"],
    "Somalia": ["Mogadishu", "Hargeisa", "Bosaso", "Kismayo", "Baidoa"],
    "South Africa": ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
    "South Korea": ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
    "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Bilbao", "Malaga"],
    "Sri Lanka": ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
    "Sudan": ["Khartoum", "Omdurman", "Port Sudan", "Kassala", "El Obeid"],
    "Sweden": ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras"],
    "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne"],
    "Tanzania": ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya"],
    "Thailand": ["Bangkok", "Chiang Mai", "Phuket", "Pattaya", "Khon Kaen"],
    "Togo": ["Lome", "Sokode", "Kara", "Kpalime", "Atakpame"],
    "Tunisia": ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
    "Turkey": ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
    "Uganda": ["Kampala", "Entebbe", "Jinja", "Gulu", "Mbarara"],
    "Ukraine": ["Kyiv", "Kharkiv", "Odesa", "Dnipro", "Lviv"],
    "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah", "Ajman", "Al Ain"],
    "United Kingdom": ["London", "Manchester", "Birmingham", "Liverpool", "Leeds", "Glasgow", "Edinburgh", "Bristol", "Cardiff", "Belfast"],
    "United States": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", "Dallas", "Miami"],
    "Uruguay": ["Montevideo", "Salto", "Paysandu", "Las Piedras", "Rivera"],
    "Venezuela": ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
    "Vietnam": ["Ho Chi Minh City", "Hanoi", "Da Nang", "Hai Phong", "Can Tho"],
    "Yemen": ["Sanaa", "Aden", "Taiz", "Hodeidah", "Ibb"],
    "Zambia": ["Lusaka", "Ndola", "Kitwe", "Livingstone", "Kabwe"],
    "Zimbabwe": ["Harare", "Bulawayo", "Mutare", "Gweru", "Masvingo"]
  };